/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trcformatter.GUI;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import trcformatter.threads.dataLoad.FileLoader;

/**
 *
 * @author ESA10969
 */
public class Loading extends javax.swing.JFrame {
  private static final long serialVersionUID = 1L;

  private final String path;
  private final String fecha;
  
  /**
   * Creates new form Loading
   * @param path
   * @param fecha
   */
  public Loading(String path, String fecha) {
    this.path = path;
    this.fecha = fecha;
    initComponents();
    putThings();
  }
  
  private void loadFile() {
    //Variable definition
    Thread th = new Thread(new FileLoader(path, this, fecha));
    
    th.start();
  }
  private void putThings() {
    //Variable definition
    JPanel contentPane;

    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    setSize(300, 320);
    contentPane = (JPanel) getContentPane();
    contentPane.setLayout(new BorderLayout());
    setTitle("Loading...");
    // add the header label
    headerLabel.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 16));
    headerLabel.setText("LOADING YOUR FILE...");
    headerLabel.setVisible(true);
    contentPane.add(headerLabel, java.awt.BorderLayout.NORTH);
    // add the image label
    ImageIcon ii = new ImageIcon(this.getClass().getResource("img/Gangnam-style.gif"));
    imageLabel.setIcon(ii);
    contentPane.add(imageLabel, java.awt.BorderLayout.CENTER);
    // show it
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    headerLabel = new javax.swing.JLabel();
    imageLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
      .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    loadFile();
  }//GEN-LAST:event_formWindowOpened


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel headerLabel;
  private javax.swing.JLabel imageLabel;
  // End of variables declaration//GEN-END:variables
}
