/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trcformatter.GUI;

import java.awt.Cursor;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trcformatter.Persistance.DAO.QueriesDAO;
import trcformatter.model.staticData.StaticData;

/**
 *
 * @author ESA10969
 */
public class LoadFile extends javax.swing.JFrame {
  private static final long serialVersionUID = 1L;

    /**
     * Creates new form LoadFile
     */
    public LoadFile() {
        initComponents();
        setRecordDates();
        setTitle("TrcFormatter V1.0");
        this.setLocationRelativeTo(null);
    }
    
    private void setRecordDates() {
      //Variable definition
      boolean data = false;
      
      Thread th = new Thread(new QueriesDAO("FECHAS", null, this, null));
    
      th.start();
      try {
        th.join();
      } catch (InterruptedException ex) {
        Logger.getLogger(LoadFile.class.getName()).log(Level.SEVERE, null, ex);
      }
      recordDates.removeAllItems();
      if(StaticData.fechas != null) {
        for(String opt : StaticData.fechas) {
          recordDates.addItem(opt);
          data = true;
        }
      }
      if(data) recordDates.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pathTxt = new javax.swing.JTextField();
    browseButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    launchLoad = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    recordDates = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    loadDate = new javax.swing.JButton();
    deleteAll = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pathTxt.setToolTipText("");

    browseButton.setText("Browse");
    browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        browseButtonMouseClicked(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel1.setText("LOAD FILE");

    launchLoad.setText("Load File");
    launchLoad.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        launchLoadMouseClicked(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setText("SELECT EXISTING RECORD");

    jLabel3.setText("Select Record Date:");

    loadDate.setText("Load");
    loadDate.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        loadDateMouseClicked(evt);
      }
    });

    deleteAll.setText("Delete");
    deleteAll.setActionCommand("Delete");
    deleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        deleteAllMouseClicked(evt);
      }
    });

    jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("TRC FORMATTER");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(pathTxt)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(browseButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recordDates, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel1)
              .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
            .addComponent(loadDate)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(deleteAll)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(167, 167, 167)
        .addComponent(launchLoad)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(recordDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(loadDate)
          .addComponent(deleteAll))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(browseButton)
          .addComponent(pathTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(launchLoad)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void browseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMouseClicked
         //Variable definition
        int returnVal;
        File file = null;
        JFileChooser fc;
         
        fc = new JFileChooser();

        returnVal = fc.showOpenDialog(LoadFile.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
           file = fc.getSelectedFile();
        }
        if(file != null && file.getPath() != null) {
            pathTxt.setText(file.getPath());
            StaticData.path = file.getPath();
        }
    }//GEN-LAST:event_browseButtonMouseClicked

  private void launchLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_launchLoadMouseClicked
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new Loading(pathTxt.getText(),null).setVisible(true);
      }
    });
    
    this.dispose();
  }//GEN-LAST:event_launchLoadMouseClicked

  private void deleteAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAllMouseClicked
    // Variable definition
    Thread th = new Thread(new QueriesDAO("DELETE", null, this, recordDates.getSelectedItem().toString()));
    
    th.start();
    try {
      th.join();
    } catch (InterruptedException ex) {
      Logger.getLogger(LoadFile.class.getName()).log(Level.SEVERE, null, ex);
    }
    JOptionPane.showMessageDialog(this, "Record Correctly Deleted", "An info message",
                                  JOptionPane.INFORMATION_MESSAGE);

    setRecordDates();
  }//GEN-LAST:event_deleteAllMouseClicked

  private void loadDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadDateMouseClicked
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new Loading(pathTxt.getText(),recordDates.getSelectedItem().toString()).setVisible(true);
      }
    });
    
    this.dispose();
  }//GEN-LAST:event_loadDateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoadFile().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton browseButton;
  private javax.swing.JButton deleteAll;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JButton launchLoad;
  private javax.swing.JButton loadDate;
  private javax.swing.JTextField pathTxt;
  private javax.swing.JComboBox recordDates;
  // End of variables declaration//GEN-END:variables
}
